Models DB / Sequelize
deep-skill/ppsh-api pull request #4
Opened 2023-06-20 01:04 UTC by SebaSatelier

adding the following models:
- Location
- w_models
- zer0 to zer7

2023-06-20 12:06 UTC, FacundoPucheta approved these changes, later dismissed
Longitude & latitude can be null? (e.g., maybe the default value must be Lima, etc.).

Other than that, it seems fine.

2023-06-20 17:30 UTC, FacundoPucheta approved these changes, later dismissed

2023-06-20 22:37 UTC, manduinca requested changes
Please, check the comments. I put some questions. Another general question is: Why do we use different ways to write the primary key?

2023-06-20 22:37 UTC, manduinca commented on src/models/Location.js
> +    pol: {
I think that `polygon` can be a more suitable name.

2023-06-20 22:37 UTC, manduinca commented on src/models/Location.js
> +
Please, delete this empty line.

2023-06-20 22:37 UTC, manduinca commented on src/models/W_one.js
> +
I think this line is unnecessary, right?

2023-06-20 22:37 UTC, manduinca commented on src/models/Zer0.js
> +        },
Please, fix the indentation.

2023-06-20 22:37 UTC, manduinca commented on src/models/Zer0.js
> +        },
Please, fix the indentation.

2023-06-20 22:37 UTC, manduinca commented on src/models/Zer0.js
> +        },
Please, fix the indentation.

2023-06-20 22:37 UTC, manduinca commented on src/models/Zer0.js
> +        },
Please, fix the indentation.

2023-06-20 22:37 UTC, manduinca commented on src/models/Zer0.js
> +        },
Please, fix the indentation.

2023-06-20 22:37 UTC, manduinca commented on src/models/Zer0.js
> +    Periodo: {
In english please, maybe `period`.

2023-06-20 22:37 UTC, manduinca commented on src/models/Zer0.js
> +                fields: ['id'], // Definir la columna 'id' como índice
I think the comment is unnecessary.

2023-06-20 22:37 UTC, manduinca commented on src/models/Zer0.js
> +                fields: ['id'], // Definir la columna 'id' como índice
If `id` is a pk. Already is not `id` an index?

2023-06-20 22:37 UTC, manduinca commented on src/models/W_one.js
> +        //primary key, autoincrement
The comment is unnecessary, I think.

2023-06-21 15:23 UTC, SebaSatelier commented
fixed indentation errors (prettier format),
change variable name pol and periodo to polygon and period,
change validate notEmpty to allowNull,
change indexes to Primary Key

2023-06-21 20:38 UTC, manduinca approved these changes
LGTM!

2023-06-21 22:17 UTC, FacundoPucheta approved these changes

2023-06-21 22:19 UTC, merged