DB connection made , Model added and controller added.
deep-skill/ppsh-api pull request #5
Opened 2023-06-20 02:16 UTC by joser098

--I've made connection to a mySQL DB. Defined using environment variables (dotnev).
In index.js You're gonna find a function called testdb that will help you to check connection with your DB.

--I've added Point_polygon model
--I've added  location_get controller
--I've added mysql2 and sequelize dependecies to package.json

2023-06-20 12:39 UTC, FacundoPucheta approved these changes, later dismissed
**location_get** 
` .findAll() can be .findOne() ?`

2023-06-20 22:52 UTC, manduinca requested changes
Please, I put some comments, review it.

2023-06-20 22:52 UTC, manduinca commented on src/controllers/serie_two_get.js
> +    const peligro = _peligro(location, tr) // get the value that peligros's function return.
Please, in english, maybe: `hazard`.

2023-06-20 22:52 UTC, manduinca commented on src/controllers/serie_two_get.js
> +const serie_two_get = (location, tr) => {
Can we search a more suitable name?, umm, maybe: `getUniformHazardSpectrum`.

2023-06-20 22:52 UTC, manduinca commented on src/controllers/location_get.js
> +const location_get = async (lat, long) => {
`getLocation`?

2023-06-20 22:52 UTC, manduinca commented on src/models/Point_polygon.js
> +    sequelize.define('Point_polygon', {
A better name can be `polygon_points`.

2023-06-20 22:52 UTC, manduinca commented on src/models/Point_polygon.js
> +            type: DataTypes.BIGINT(11),
Why not `INTEGER`?

2023-06-21 15:37 UTC, SebaSatelier approved these changes
looks fine, some indentation errors but nothing serious. That can be change later

2023-06-21 20:46 UTC, manduinca approved these changes
I leaved some commenta, I approved it.

2023-06-21 20:46 UTC, manduinca commented on src/db.js
> +
One empty line is sufficient here.

2023-06-21 20:46 UTC, manduinca commented on src/db.js
> +
Only one blank line, I think.

2023-06-21 20:46 UTC, manduinca commented on src/controllers/getLocations.js
> +    // Get lat and long by query.
These comments are not necessaries. Your code explain it.

2023-06-21 20:46 UTC, manduinca commented on index.js
> +// ###### FUNCTION TO TEST CONNECTION WITH DATABASE ######
Do we need these comments?

2023-06-22 13:37 UTC, merged